// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package capture

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type pgtraceEvent struct {
	_        structs.HostLayout
	Ts       uint64
	Tgid     uint32
	Fd       int32
	TotalLen uint32
	CapLen   uint32
	Kind     uint8
	Dir      uint8
	Family   uint16
	Port     [2]uint8
	Pad      [2]uint8
	Addr     [16]uint8
	Payload  [4096]uint8
}

type pgtraceFdKey struct {
	_    structs.HostLayout
	Tgid uint32
	Fd   int32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	pgtraceMapDrops         = "drops"
	pgtraceMapEvents        = "events"
	pgtraceMapFdClass       = "fd_class"
	pgtraceMapScratch       = "scratch"
	pgtraceMapTargetPids    = "target_pids"
	pgtraceProgEnterClose   = "enter_close"
	pgtraceProgExitConnect  = "exit_connect"
	pgtraceProgExitRecvfrom = "exit_recvfrom"
	pgtraceProgExitSendto   = "exit_sendto"
)

// loadPgtrace returns the embedded CollectionSpec for pgtrace.
func loadPgtrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PgtraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load pgtrace: %w", err)
	}

	return spec, err
}

// loadPgtraceObjects loads pgtrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*pgtraceObjects
//	*pgtracePrograms
//	*pgtraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadPgtraceObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadPgtrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// pgtraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pgtraceSpecs struct {
	pgtraceProgramSpecs
	pgtraceMapSpecs
	pgtraceVariableSpecs
}

// pgtraceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pgtraceProgramSpecs struct {
	EnterClose   *ebpf.ProgramSpec `ebpf:"enter_close"`
	ExitConnect  *ebpf.ProgramSpec `ebpf:"exit_connect"`
	ExitRecvfrom *ebpf.ProgramSpec `ebpf:"exit_recvfrom"`
	ExitSendto   *ebpf.ProgramSpec `ebpf:"exit_sendto"`
}

// pgtraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pgtraceMapSpecs struct {
	Drops      *ebpf.MapSpec `ebpf:"drops"`
	Events     *ebpf.MapSpec `ebpf:"events"`
	FdClass    *ebpf.MapSpec `ebpf:"fd_class"`
	Scratch    *ebpf.MapSpec `ebpf:"scratch"`
	TargetPids *ebpf.MapSpec `ebpf:"target_pids"`
}

// pgtraceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pgtraceVariableSpecs struct {
}

// pgtraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadPgtraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type pgtraceObjects struct {
	pgtracePrograms
	pgtraceMaps
	pgtraceVariables
}

func (o *pgtraceObjects) Close() error {
	return _PgtraceClose(
		&o.pgtracePrograms,
		&o.pgtraceMaps,
	)
}

// pgtraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadPgtraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type pgtraceMaps struct {
	Drops      *ebpf.Map `ebpf:"drops"`
	Events     *ebpf.Map `ebpf:"events"`
	FdClass    *ebpf.Map `ebpf:"fd_class"`
	Scratch    *ebpf.Map `ebpf:"scratch"`
	TargetPids *ebpf.Map `ebpf:"target_pids"`
}

func (m *pgtraceMaps) Close() error {
	return _PgtraceClose(
		m.Drops,
		m.Events,
		m.FdClass,
		m.Scratch,
		m.TargetPids,
	)
}

// pgtraceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadPgtraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type pgtraceVariables struct {
}

// pgtracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadPgtraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type pgtracePrograms struct {
	EnterClose   *ebpf.Program `ebpf:"enter_close"`
	ExitConnect  *ebpf.Program `ebpf:"exit_connect"`
	ExitRecvfrom *ebpf.Program `ebpf:"exit_recvfrom"`
	ExitSendto   *ebpf.Program `ebpf:"exit_sendto"`
}

func (p *pgtracePrograms) Close() error {
	return _PgtraceClose(
		p.EnterClose,
		p.ExitConnect,
		p.ExitRecvfrom,
		p.ExitSendto,
	)
}

func _PgtraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed pgtrace_x86_bpfel.o
var _PgtraceBytes []byte
