// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package capture

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type pgtraceArgs struct {
	_         structs.HostLayout
	Buf       uint64
	Fd        int32
	Dir       uint8
	IsConnect uint8
	Family    uint16
	Port      [2]uint8
	Addr      [16]uint8
	_         [6]byte
}

type pgtraceEvent struct {
	_        structs.HostLayout
	Ts       uint64
	Tgid     uint32
	Fd       int32
	TotalLen uint32
	CapLen   uint32
	Kind     uint8
	Dir      uint8
	Family   uint16
	Port     [2]uint8
	Pad      [2]uint8
	Addr     [16]uint8
	Payload  [4096]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	pgtraceMapActive         = "active"
	pgtraceMapDrops          = "drops"
	pgtraceMapEvents         = "events"
	pgtraceMapScratch        = "scratch"
	pgtraceMapTargetPids     = "target_pids"
	pgtraceProgEnterClose    = "enter_close"
	pgtraceProgEnterConnect  = "enter_connect"
	pgtraceProgEnterRead     = "enter_read"
	pgtraceProgEnterRecvfrom = "enter_recvfrom"
	pgtraceProgEnterSendto   = "enter_sendto"
	pgtraceProgEnterWrite    = "enter_write"
	pgtraceProgExitConnect   = "exit_connect"
	pgtraceProgExitRead      = "exit_read"
	pgtraceProgExitRecvfrom  = "exit_recvfrom"
	pgtraceProgExitSendto    = "exit_sendto"
	pgtraceProgExitWrite     = "exit_write"
)

// loadPgtrace returns the embedded CollectionSpec for pgtrace.
func loadPgtrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PgtraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load pgtrace: %w", err)
	}

	return spec, err
}

// loadPgtraceObjects loads pgtrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*pgtraceObjects
//	*pgtracePrograms
//	*pgtraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadPgtraceObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadPgtrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// pgtraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pgtraceSpecs struct {
	pgtraceProgramSpecs
	pgtraceMapSpecs
	pgtraceVariableSpecs
}

// pgtraceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pgtraceProgramSpecs struct {
	EnterClose    *ebpf.ProgramSpec `ebpf:"enter_close"`
	EnterConnect  *ebpf.ProgramSpec `ebpf:"enter_connect"`
	EnterRead     *ebpf.ProgramSpec `ebpf:"enter_read"`
	EnterRecvfrom *ebpf.ProgramSpec `ebpf:"enter_recvfrom"`
	EnterSendto   *ebpf.ProgramSpec `ebpf:"enter_sendto"`
	EnterWrite    *ebpf.ProgramSpec `ebpf:"enter_write"`
	ExitConnect   *ebpf.ProgramSpec `ebpf:"exit_connect"`
	ExitRead      *ebpf.ProgramSpec `ebpf:"exit_read"`
	ExitRecvfrom  *ebpf.ProgramSpec `ebpf:"exit_recvfrom"`
	ExitSendto    *ebpf.ProgramSpec `ebpf:"exit_sendto"`
	ExitWrite     *ebpf.ProgramSpec `ebpf:"exit_write"`
}

// pgtraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pgtraceMapSpecs struct {
	Active     *ebpf.MapSpec `ebpf:"active"`
	Drops      *ebpf.MapSpec `ebpf:"drops"`
	Events     *ebpf.MapSpec `ebpf:"events"`
	Scratch    *ebpf.MapSpec `ebpf:"scratch"`
	TargetPids *ebpf.MapSpec `ebpf:"target_pids"`
}

// pgtraceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pgtraceVariableSpecs struct {
}

// pgtraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadPgtraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type pgtraceObjects struct {
	pgtracePrograms
	pgtraceMaps
	pgtraceVariables
}

func (o *pgtraceObjects) Close() error {
	return _PgtraceClose(
		&o.pgtracePrograms,
		&o.pgtraceMaps,
	)
}

// pgtraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadPgtraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type pgtraceMaps struct {
	Active     *ebpf.Map `ebpf:"active"`
	Drops      *ebpf.Map `ebpf:"drops"`
	Events     *ebpf.Map `ebpf:"events"`
	Scratch    *ebpf.Map `ebpf:"scratch"`
	TargetPids *ebpf.Map `ebpf:"target_pids"`
}

func (m *pgtraceMaps) Close() error {
	return _PgtraceClose(
		m.Active,
		m.Drops,
		m.Events,
		m.Scratch,
		m.TargetPids,
	)
}

// pgtraceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadPgtraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type pgtraceVariables struct {
}

// pgtracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadPgtraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type pgtracePrograms struct {
	EnterClose    *ebpf.Program `ebpf:"enter_close"`
	EnterConnect  *ebpf.Program `ebpf:"enter_connect"`
	EnterRead     *ebpf.Program `ebpf:"enter_read"`
	EnterRecvfrom *ebpf.Program `ebpf:"enter_recvfrom"`
	EnterSendto   *ebpf.Program `ebpf:"enter_sendto"`
	EnterWrite    *ebpf.Program `ebpf:"enter_write"`
	ExitConnect   *ebpf.Program `ebpf:"exit_connect"`
	ExitRead      *ebpf.Program `ebpf:"exit_read"`
	ExitRecvfrom  *ebpf.Program `ebpf:"exit_recvfrom"`
	ExitSendto    *ebpf.Program `ebpf:"exit_sendto"`
	ExitWrite     *ebpf.Program `ebpf:"exit_write"`
}

func (p *pgtracePrograms) Close() error {
	return _PgtraceClose(
		p.EnterClose,
		p.EnterConnect,
		p.EnterRead,
		p.EnterRecvfrom,
		p.EnterSendto,
		p.EnterWrite,
		p.ExitConnect,
		p.ExitRead,
		p.ExitRecvfrom,
		p.ExitSendto,
		p.ExitWrite,
	)
}

func _PgtraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed pgtrace_x86_bpfel.o
var _PgtraceBytes []byte
