// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package capture

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tlsCur struct {
	_   structs.HostLayout
	Ssl uint64
	Buf uint64
}

type tlsEvent struct {
	_        structs.HostLayout
	Ts       uint64
	Tgid     uint32
	Fd       int32
	TotalLen uint32
	CapLen   uint32
	Kind     uint8
	Dir      uint8
	Family   uint16
	Port     [2]uint8
	Pad      [2]uint8
	Addr     [16]uint8
	Seq      uint32
	Flags    uint32
	Payload  [16384]uint8
}

type tlsFdKey struct {
	_    structs.HostLayout
	Tgid uint32
	Fd   int32
}

type tlsSessKey struct {
	_    structs.HostLayout
	Tgid uint32
	Pad  uint32
	Ssl  uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	tlsMapDrops          = "drops"
	tlsMapEvents         = "events"
	tlsMapFdClass        = "fd_class"
	tlsMapScratch        = "scratch"
	tlsMapTargetPids     = "target_pids"
	tlsMapTlsCurrent     = "tls_current"
	tlsMapTlsFallback    = "tls_fallback"
	tlsMapTlsInfoSsl     = "tls_info_ssl"
	tlsMapTlsSessions    = "tls_sessions"
	tlsProgFallbackRead  = "fallback_read"
	tlsProgFallbackWrite = "fallback_write"
	tlsProgSslCipherExit = "ssl_cipher_exit"
	tlsProgSslFree       = "ssl_free"
	tlsProgSslReadEnter  = "ssl_read_enter"
	tlsProgSslReadExit   = "ssl_read_exit"
	tlsProgSslSetRfd     = "ssl_set_rfd"
	tlsProgSslVerEnter   = "ssl_ver_enter"
	tlsProgSslVerExit    = "ssl_ver_exit"
	tlsProgSslWrite      = "ssl_write"
	tlsProgSslWriteRet   = "ssl_write_ret"
	tlsVarCaptureBytes   = "capture_bytes"
)

// loadTls returns the embedded CollectionSpec for tls.
func loadTls() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TlsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tls: %w", err)
	}

	return spec, err
}

// loadTlsObjects loads tls and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tlsObjects
//	*tlsPrograms
//	*tlsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTlsObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTls()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tlsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsSpecs struct {
	tlsProgramSpecs
	tlsMapSpecs
	tlsVariableSpecs
}

// tlsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsProgramSpecs struct {
	FallbackRead  *ebpf.ProgramSpec `ebpf:"fallback_read"`
	FallbackWrite *ebpf.ProgramSpec `ebpf:"fallback_write"`
	SslCipherExit *ebpf.ProgramSpec `ebpf:"ssl_cipher_exit"`
	SslFree       *ebpf.ProgramSpec `ebpf:"ssl_free"`
	SslReadEnter  *ebpf.ProgramSpec `ebpf:"ssl_read_enter"`
	SslReadExit   *ebpf.ProgramSpec `ebpf:"ssl_read_exit"`
	SslSetRfd     *ebpf.ProgramSpec `ebpf:"ssl_set_rfd"`
	SslVerEnter   *ebpf.ProgramSpec `ebpf:"ssl_ver_enter"`
	SslVerExit    *ebpf.ProgramSpec `ebpf:"ssl_ver_exit"`
	SslWrite      *ebpf.ProgramSpec `ebpf:"ssl_write"`
	SslWriteRet   *ebpf.ProgramSpec `ebpf:"ssl_write_ret"`
}

// tlsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsMapSpecs struct {
	Drops       *ebpf.MapSpec `ebpf:"drops"`
	Events      *ebpf.MapSpec `ebpf:"events"`
	FdClass     *ebpf.MapSpec `ebpf:"fd_class"`
	Scratch     *ebpf.MapSpec `ebpf:"scratch"`
	TargetPids  *ebpf.MapSpec `ebpf:"target_pids"`
	TlsCurrent  *ebpf.MapSpec `ebpf:"tls_current"`
	TlsFallback *ebpf.MapSpec `ebpf:"tls_fallback"`
	TlsInfoSsl  *ebpf.MapSpec `ebpf:"tls_info_ssl"`
	TlsSessions *ebpf.MapSpec `ebpf:"tls_sessions"`
}

// tlsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsVariableSpecs struct {
	CaptureBytes *ebpf.VariableSpec `ebpf:"capture_bytes"`
}

// tlsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsObjects struct {
	tlsPrograms
	tlsMaps
	tlsVariables
}

func (o *tlsObjects) Close() error {
	return _TlsClose(
		&o.tlsPrograms,
		&o.tlsMaps,
	)
}

// tlsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsMaps struct {
	Drops       *ebpf.Map `ebpf:"drops"`
	Events      *ebpf.Map `ebpf:"events"`
	FdClass     *ebpf.Map `ebpf:"fd_class"`
	Scratch     *ebpf.Map `ebpf:"scratch"`
	TargetPids  *ebpf.Map `ebpf:"target_pids"`
	TlsCurrent  *ebpf.Map `ebpf:"tls_current"`
	TlsFallback *ebpf.Map `ebpf:"tls_fallback"`
	TlsInfoSsl  *ebpf.Map `ebpf:"tls_info_ssl"`
	TlsSessions *ebpf.Map `ebpf:"tls_sessions"`
}

func (m *tlsMaps) Close() error {
	return _TlsClose(
		m.Drops,
		m.Events,
		m.FdClass,
		m.Scratch,
		m.TargetPids,
		m.TlsCurrent,
		m.TlsFallback,
		m.TlsInfoSsl,
		m.TlsSessions,
	)
}

// tlsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsVariables struct {
	CaptureBytes *ebpf.Variable `ebpf:"capture_bytes"`
}

// tlsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsPrograms struct {
	FallbackRead  *ebpf.Program `ebpf:"fallback_read"`
	FallbackWrite *ebpf.Program `ebpf:"fallback_write"`
	SslCipherExit *ebpf.Program `ebpf:"ssl_cipher_exit"`
	SslFree       *ebpf.Program `ebpf:"ssl_free"`
	SslReadEnter  *ebpf.Program `ebpf:"ssl_read_enter"`
	SslReadExit   *ebpf.Program `ebpf:"ssl_read_exit"`
	SslSetRfd     *ebpf.Program `ebpf:"ssl_set_rfd"`
	SslVerEnter   *ebpf.Program `ebpf:"ssl_ver_enter"`
	SslVerExit    *ebpf.Program `ebpf:"ssl_ver_exit"`
	SslWrite      *ebpf.Program `ebpf:"ssl_write"`
	SslWriteRet   *ebpf.Program `ebpf:"ssl_write_ret"`
}

func (p *tlsPrograms) Close() error {
	return _TlsClose(
		p.FallbackRead,
		p.FallbackWrite,
		p.SslCipherExit,
		p.SslFree,
		p.SslReadEnter,
		p.SslReadExit,
		p.SslSetRfd,
		p.SslVerEnter,
		p.SslVerExit,
		p.SslWrite,
		p.SslWriteRet,
	)
}

func _TlsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tls_x86_bpfel.o
var _TlsBytes []byte
